install:
- pip install --user awscli
- wget https://github.com/gohugoio/hugo/releases/download/v0.84.4/hugo_0.84.4_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- hugo version

before_script:
- rm -rf public
- hugo

script:
- aws s3 sync. s3://kelvtan.space --acl public-read --delete
- aws cloudfront create-invalidation --distribution-id E1ZKK7CQQDBWKJ --paths '/*'

branches:
 only:
 - master

